### ISSUE TITLE
build index for hbase

### ISSUE THREAD

**Issue by at15** [at15/cs433#7]
for instance we have a htable like this 

```
rowkey  info:name info:email
1            jack          jack@123.com
2            dick          dick@123.com
```

we need a table to index this table by info:name

```
rowkey row
dick       2
jack      1
```

use mapreduce to do this
- [x] setup hbase with existing hadoop
- [x] write fake data 
- [x] write the mapper 
- [x] see the result
- [x] send mail to TA

**Comment by at15** [comment]
why I only knew this today .... e ....

**Comment by at15** [comment]
some refs

http://www.informit.com/articles/article.aspx?p=2262143&seqNum=2

**Comment by at15** [comment]
```
Exception in thread "main" org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: contacts: 1 time, 
    at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.makeException(AsyncProcess.java:228)
    at org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.access$1700(AsyncProcess.java:208)
    at org.apache.hadoop.hbase.client.AsyncProcess.waitForAllPreviousOpsAndReset(AsyncProcess.java:1689)
    at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:208)
    at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:183)
    at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1449)
    at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1040)
    at cn.edu.sjtu.stu.at15.hbase.Seeder.main(Seeder.java:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

this is caused by
- not creating table/column family

the class won't create the table automatically I guess ....

**Comment by at15** [comment]
https://books.google.com/books?id=nUhiQxUXVpMC HBase: The Definitive Guide

**Comment by at15** [comment]
the exact example .... https://github.com/apache/hbase/blob/master/hbase-examples/src/main/java/org/apache/hadoop/hbase/mapreduce/IndexBuilder.java

**Comment by at15** [comment]
finished in 60c1b8356f60c434367b620e8828ef85d7afec08
